site_name: EH Forwarder Bot
pages:
    - 'Home': 'index.md'
    - 'Installation': 'installation.md'
    - 'Getting started': 'getting-started.md'
    - 'Channels repository': 'channels-repository.md'
    - 'Your first channel':
        - 'EFB workflow': 'workflow.md'
        - 'Slave Channel': 'slave-channel.md'
        - 'Master Channel': 'master-channel.md'
    - 'API Documentation':
        - 'EFBMsg': 'message.md'
        - 'EFBChannel': 'channel.md'
        - 'Exceptions': 'exceptions.md'
    - 'Contributing': 'CONTRIBUTING.md'
    - 'Official plugins':
        - 'EFB Telegram Master': 'ETM.md'
        - 'EFB WeChat Slave': 'EWS.md'
theme: readthedocs
repo_url: 'https://github.com/blueset/ehforwarderbot'
